### ISSUE TITLE
Program.cs not working

### ISSUE THREAD

**Issue by daira5555** [Ian-Liceranzu/BasketLeague#1]
**Hola buenas** verás tengo un problema con este proyecto el problema es el siguiente: no he ganado yo. Me gustaría que se solucionara este claro bug para la siguiente liga aquí te dejo una sugerencia

```
for (int i = 0; i < teams.Count; i++)
{
	if(teams[i].NombreCompleto == "Seattle Killer Whales") Console.WriteLine("Felicidades Daira");
}
```

Muchas gracias por tu atención, un saludo

**Comment by Ian-Liceranzu** [comment]
*Hola buenas tardes*
Agradezco que se haya puesto en contacto conmigo.
Me pondré con ello a no más tardar, en cuanto esté implementado cerraré el hilo.
Un saludo
